# Generated by Django 5.1.1 on 2024-09-15 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название дилера')),
                ('headquarters_location', models.TextField(verbose_name='Местоположение главного офиса')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.TextField(verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.TextField(verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.TextField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.TextField(verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('contact_info', models.TextField(verbose_name='Контактная информация')),
                ('car_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.car')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='DealerCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarters_location', models.TextField(verbose_name='Местоположение центра')),
                ('contact', models.TextField(verbose_name='Контактная информация')),
                ('manager', models.TextField(verbose_name='Имя управляющего')),
                ('dealer_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.dealer')),
            ],
            options={
                'verbose_name': 'Дилерский центр',
                'verbose_name_plural': 'Дилерские центры',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='dealer_center_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.dealercenter'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_data', models.TextField(verbose_name='Дата продажи')),
                ('sale_price', models.TextField(verbose_name='Цена продажи')),
                ('car_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.car')),
                ('dealer_center_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.dealercenter')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
    ]
