# Generated by Django 5.1.1 on 2024-09-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0002_dealer_alter_car_options_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.customer'),
        ),
    ]
