# Generated by Django 5.1 on 2024-10-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0003_sale_customer_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='dealer_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.dealer', verbose_name='Дилерский центр'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer_center_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.dealercenter', verbose_name='Дилерский центр'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='car_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='dealercenter',
            name='dealer_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.dealer', verbose_name='Дилерский центр'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='car_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dealer_center_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsales.dealercenter', verbose_name='Дилерский центр'),
        ),
    ]
