# Generated by Django 5.1 on 2024-10-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0004_remove_car_brand_car_dealer_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='dealer_center_FK',
        ),
    ]
