# Generated by Django 5.1 on 2024-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0005_remove_sale_dealer_center_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='cars', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='picture',
            field=models.ImageField(null=True, upload_to='dealers', verbose_name='Изображение'),
        ),
    ]
