# Generated by Django 5.1 on 2024-10-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0006_car_picture_dealer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_data',
            field=models.DateField(verbose_name='Дата продажи'),
        ),
    ]
