# Generated by Django 5.1 on 2024-12-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0009_tradein'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeIn',
        ),
    ]
