# Generated by Django 5.1 on 2024-12-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0010_delete_tradein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
