# Generated by Django 5.1 on 2024-12-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0011_alter_car_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
